name: "openapi-swagger-remote-schema"

static-env:
  HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
  HASURA_GRAPHQL_EXPERIMENTAL_FEATURES: "inherited_roles"
  HASURA_GRAPHQL_ENABLE_REMOTE_SCHEMA_PERMISSIONS: true

user-env:
  OPENAPI_SWAGGER_ENDPOINT:
    default: "http://localhost:3000"
    description: "OpenAPI Swagger Endpoint"
    mandatory: true
