name: "magento-remote-schema"

static-env:
  HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
  HASURA_GRAPHQL_EXPERIMENTAL_FEATURES: "inherited_roles"
  HASURA_GRAPHQL_ENABLE_REMOTE_SCHEMA_PERMISSIONS: true

user-env:
  MAGENTO_GRAPHQL_ENDPOINT:
    default: "https://<magento-store-url>/graphql"
    description: "Magento GraphQL Endpoint"
    mandatory: true
