name: "github-remote-schema"

static-env:
  HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
  HASURA_GRAPHQL_EXPERIMENTAL_FEATURES: "inherited_roles"
  HASURA_GRAPHQL_ENABLE_REMOTE_SCHEMA_PERMISSIONS: true

user-env:
  GITHUB_PERSONAL_ACCESS_TOKEN:
    default: "Bearer <API Access Token>"
    description: "GitHub Personal Access Token https://docs.github.com/en/graphql/guides/forming-calls-with-graphql#authenticating-with-graphql"
    mandatory: true
