name: "hygraph-remote-schema"

static-env:
  HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
  HASURA_GRAPHQL_EXPERIMENTAL_FEATURES: "inherited_roles"
  HASURA_GRAPHQL_ENABLE_REMOTE_SCHEMA_PERMISSIONS: true

user-env:
  HYGRAPH_CONTENT_API_ENDPOINT:
    description: "Content API endpoint of Hygraph"
    mandatory: true
  HYGRAPH_PERMANENT_AUTH_TOKEN:
    default: "Bearer <API Access Token>"
    description: "Hygraph Permanent auth tokens https://hygraph.com/docs/api-reference/basics/authorization#permanent-auth-tokens"
    mandatory: true
