name: "netlify-event-transform"

static-env:
  HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous

user-env:
  NETLIFY_BUILD_HOOK:
    default: "https://api.netlify.com/build_hooks/XXXXXXXXXXXXXXX"
    description: "Check out Netlify Docs on creating and configuring a build hook https://docs.netlify.com/configure-builds/build-hooks/"
    mandatory: true
