name: "algolia-action-transform"

static-env:
  HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous

user-env:
  ALGOLIA_API_KEY:
    default: "xxxxxxxxxxxxxxxxx"
    description: "Check out Algolia Docs on Creating and Managing API key https://www.algolia.com/doc/guides/security/api-keys/#creating-and-managing-api-keys"
    mandatory: true
  ALGOLIA_APPLICATION_ID:
    default: "application-id"
    description: "The ID of your application"
    mandatory: true
  ALGOLIA_INDEX_NAME:
    default: "some-index-name"
    description: "Your index name"
    mandatory: true
