name: "wordpress-remote-schema"

static-env:
  HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
  HASURA_GRAPHQL_EXPERIMENTAL_FEATURES: "inherited_roles"
  HASURA_GRAPHQL_ENABLE_REMOTE_SCHEMA_PERMISSIONS: true

user-env:
  WORDPRESS_GRAPHQL_ENDPOINT:
    default: "<Wordpress URL>/graphql"
    description: "Wordpress GraphQL endpoint"
    mandatory: true
