name: "sendgrid-event-transform"

static-env:
  HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous

user-env:
  SENDGRID_API_KEY:
    default: "Bearer xxxxxx"
    description: "Check out Sendgrid dashboard on creating an API key https://app.sendgrid.com/settings/api_keys"
    mandatory: true
